### PR TITLE
Create 2 better examples for Cross Chain

### PR DESCRIPTION
**Pull request by ardatan**

### CODE REVIEW

**Comment by matthewlilley** [comment]
Maybe a good idea to seperate these examples instead of replacing one with the other.

**Comment by ardatan** [comment]
@matthewlilley You're right but I think we can have better example for the older approach. So I brought it back with some improvements

**Comment by matthewlilley** [comment]
@ardatan Great! Seeing these different approaches are a great help to us so thank you.

**Review by dotansimha — APPROVED** [review]
@ardatan looks great. Just a rebase is needed and we can merge :)

**Pull request merged**
